# Generated by Django 4.2.9 on 2024-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkpayment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
