# Generated by Django 4.2.9 on 2024-02-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order_checkpayment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_massage', models.TextField(blank=True, max_length=500)),
                ('cancel_check', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='pending', max_length=20)),
                ('test', models.TextField(blank=True, max_length=500, null=True)),
                ('old_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.old_cartitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
    ]
