# Generated by Django 4.2.9 on 2024-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cancellation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='request_massage',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
