# Generated by Django 4.2.9 on 2024-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_product_prod_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image3',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
    ]
