# Generated by Django 4.2.9 on 2024-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product_prod_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('All Belts', 'All Belts'), ('Signature Belts', 'Signature Belts'), ('Reversible Belts', 'Reversible Belts'), ('Casual Belts', 'Casual Belts'), ('Wallets', 'Wallets'), ('Accessories', 'Accessories'), ('Corporate Gifts', 'Corporate Gifts')], max_length=50, null=True),
        ),
    ]
