# Generated by Django 4.2.9 on 2024-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_size_34_product_size_36_product_size_38_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('All Belts', 'All Belts'), ('Signature Belts', 'Signature Belts'), ('Reversible Belts', 'Reversible Belts'), ('Casual Belts', 'Casual Belts'), ('Formal Belts', 'Formal Belts'), ('Wallets', 'Wallets'), ('Accessories', 'Accessories'), ('Corporate Gifts', 'Corporate Gifts')], max_length=50, null=True),
        ),
    ]
