# Generated by Django 4.2.9 on 2024-03-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('All Belts', 'All Belts'), ('Signature Belts', 'Signature Belts'), ('Reversible Belts', 'Reversible Belts'), ('Casual Belts', 'Casual Belts'), ('Semi Formal ', 'Semi Formal '), ('Braided/Ladies Belt', 'Braided/Ladies Belt'), ('Formal Belts', 'Formal Belts'), ('Wallets', 'Wallets'), ('Accessories', 'Accessories'), ('Corporate Gifts', 'Corporate Gifts')], max_length=50, null=True),
        ),
    ]
