# Generated by Django 4.2.9 on 2024-04-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b2b',
            field=models.BooleanField(default=False),
        ),
    ]
