# Generated by Django 4.2.9 on 2024-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_product_b2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image1',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image2',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image3',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image_detail',
            field=models.ImageField(default='None', upload_to='productimgdetail'),
        ),
    ]
