# Generated by Django 4.2.9 on 2024-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_product_prod_image1_alter_product_prod_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image1',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image2',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image3',
            field=models.ImageField(blank=True, null=True, upload_to='productimg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image_detail',
            field=models.ImageField(upload_to='productimgdetail'),
        ),
    ]
