# Generated by Django 4.2.9 on 2024-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('All Belts', 'All Belts'), ('Signature Belts', 'Signature Belts'), ('Casual Belts', 'Casual Belts'), ('Semi Formal', 'Semi Formal'), ('Ladies Belt', 'Ladies Belt'), ('Formal Belts', 'Formal Belts'), ('Wallets', 'Wallets'), ('Accessories', 'Accessories'), ('Corporate Gifts', 'Corporate Gifts'), ('Under799', 'Under799')], max_length=50, null=True),
        ),
    ]
